#kube config for tictactoe local run
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoegame-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe-ui
  template:
    metadata:
      labels:
        app: tictactoe-ui
    spec:
      containers:
      - name: tictactoe-ui-container
        image: srinivasv147/tictactoe-ui
---
apiVersion: v1
kind: Service
metadata:
  name: ttt-ui-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: tictactoe-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002